### PR TITLE
Fix bundle product partial refunds

### PR DESCRIPTION
**Pull request by ryanreeves-taxjar**
### Context
Credit memo line items were being calculated incorrectly for bundled products because the product type of bundled products couldn't be determined.  This change fixes that bug by loading the original order item and getting the product type from it.

### Description
This PR fixes the missing product type for bundled products.  Previously the parent bundled item was refunded regardless of which specific children were refunded.  Now the refunded child items are reported correctly.  

### Performance
This PR has no measurable impact on performance.

### Testing
1. Create an order with a bundled product.  
Screen Shot 2020-04-01 at 5 07 21 PM

2. Create a credit memo that only refunds part of the original items.
Screen Shot 2020-04-01 at 5 07 49 PM

3. Confirm only the refunded items were reported to TaxJar
Screen Shot 2020-04-01 at 5 07 57 PM

#### Versions

- [X] Magento 2.3
- [X] Magento 2.2
- [X] Magento 2.1

- [X] Magento Open Source (CE)
- [X] Magento Commerce (EE)
- [ ] Magento B2B
- [ ] Magento Cloud

- [X] PHP 7.x
- [ ] PHP 5.x

### CODE REVIEW

**Review by dallendalton — APPROVED** [review]

**Review by mdrobbins — APPROVED** [review]
Looks good to me.

**Comment by fastdivision** [comment]
@ryanreeves-taxjar Merge conflict

**Comment by ryanreeves-taxjar** [comment]
Merge conflict resolved; check branch INT-641-integration-testing

**Comment by ryanreeves-taxjar** [comment]
Closing this PR as the code was merged into https://github.com/taxjar/taxjar-magento2-extension/pull/128

**Pull request closed without merging**
